language: node_js
sudo: false
env:
  - CXX=g++-4.8
node_js:
  - "4.1"
  - "4.0"
  - "iojs"
  - "iojs-v2"
addons:
  postgresql: 9.4
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - cp config.js.tmpl config.js